const departmentAdmin = {
  id: 1,
  code: 'ADMIN',
  name: 'Администрация',
  active: true,
};

const departmentServices = {
  id: 2,
  code: 'SERV',
  name: 'Служебные подразделения',
  active: true,
};

const users = [
  {
    id: 1,
    fullName: 'Администратор системы',
    email: 'admin@prosvet.ru',
    username: 'admin',
    role: 'ADMIN',
    department: departmentAdmin,
    position: 'Администратор',
    active: true,
  },
  {
    id: 2,
    fullName: 'Иван Петров',
    email: 'ivan.petrov@prosvet.ru',
    username: 'ipetrov',
    role: 'EMPLOYEE',
    department: departmentServices,
    position: 'Специалист',
    active: true,
  },
  {
    id: 3,
    fullName: 'Ольга Сидорова',
    email: 'olga.sidorova@prosvet.ru',
    username: 'osidorova',
    role: 'RESPONSIBLE',
    department: departmentAdmin,
    position: 'Ответственный за заявки и склад',
    active: true,
  },
];

const categories = [
  { id: 1, name: 'Бумага и блокноты', description: 'Бумажная продукция' },
  { id: 2, name: 'Письменные принадлежности', description: 'Ручки, карандаши, маркеры' },
  { id: 3, name: 'Организация документов', description: 'Папки, файлы, скрепление' },
];

const items = [
  {
    id: 1,
    name: 'Бумага A4',
    sku: 'A4-001',
    category: categories[0],
    unit: 'пачка',
    currentQuantity: 48,
    minQuantity: 10,
    storageLocation: 'Склад 1',
    description: 'Бумага A4 для нужд учреждения',
    active: true,
  },
  {
    id: 2,
    name: 'Ручка шариковая синяя',
    sku: 'PEN-002',
    category: categories[1],
    unit: 'шт',
    currentQuantity: 180,
    minQuantity: 30,
    storageLocation: 'Склад 1',
    description: 'Ручка шариковая синяя для нужд учреждения',
    active: true,
  },
  {
    id: 3,
    name: 'Карандаш HB',
    sku: 'PEN-003',
    category: categories[1],
    unit: 'шт',
    currentQuantity: 96,
    minQuantity: 20,
    storageLocation: 'Склад 1',
    description: 'Карандаш HB для нужд учреждения',
    active: true,
  },
  {
    id: 4,
    name: 'Папка-скоросшиватель',
    sku: 'FIL-004',
    category: categories[2],
    unit: 'шт',
    currentQuantity: 64,
    minQuantity: 15,
    storageLocation: 'Склад 2',
    description: 'Папка-скоросшиватель для нужд учреждения',
    active: true,
  },
  {
    id: 5,
    name: 'Файл прозрачный',
    sku: 'FIL-005',
    category: categories[2],
    unit: 'шт',
    currentQuantity: 240,
    minQuantity: 60,
    storageLocation: 'Склад 2',
    description: 'Файл прозрачный для нужд учреждения',
    active: true,
  },
  {
    id: 6,
    name: 'Стикеры',
    sku: 'OFF-006',
    category: categories[0],
    unit: 'упак',
    currentQuantity: 18,
    minQuantity: 5,
    storageLocation: 'Склад 1',
    description: 'Стикеры для нужд учреждения',
    active: true,
  },
];

const requests = [
  {
    id: 1,
    requestNumber: 'REQ-20260507-0001',
    requester: users[1],
    department: departmentServices,
    status: 'SUBMITTED',
    priority: 'NORMAL',
    comment: 'Запрос на текущую неделю',
    approvedBy: null,
    approvedAt: null,
    rejectionReason: null,
    createdAt: '2026-05-07T08:20:00Z',
    updatedAt: '2026-05-07T08:20:00Z',
    items: [
      {
        id: 1,
        item: items[0],
        quantityRequested: 2,
        quantityIssued: 0,
        note: 'Для принтера',
      },
      {
        id: 2,
        item: items[1],
        quantityRequested: 10,
        quantityIssued: 0,
        note: 'Для сотрудников',
      },
    ],
  },
  {
    id: 2,
    requestNumber: 'REQ-20260506-0002',
    requester: users[1],
    department: departmentServices,
    status: 'APPROVED',
    priority: 'HIGH',
    comment: 'Срочная заявка для делопроизводства',
    approvedBy: users[2],
    approvedAt: '2026-05-06T11:10:00Z',
    rejectionReason: null,
    createdAt: '2026-05-06T10:30:00Z',
    updatedAt: '2026-05-06T11:10:00Z',
    items: [
      {
        id: 3,
        item: items[3],
        quantityRequested: 4,
        quantityIssued: 0,
        note: 'Для архивирования',
      },
    ],
  },
];

const movements = [
  {
    id: 1,
    type: 'RECEIPT',
    item: items[0],
    quantity: 20,
    happenedAt: '2026-05-05T07:30:00Z',
    sourceDocument: 'Поступление №15',
    actor: users[2],
    comment: 'Поставка от поставщика',
  },
  {
    id: 2,
    type: 'ISSUE',
    item: items[1],
    quantity: 10,
    happenedAt: '2026-05-06T12:05:00Z',
    sourceDocument: 'REQ-20260506-0002',
    actor: users[2],
    comment: 'Выдача по согласованной заявке',
  },
];

export const mockSeedData = {
  departments: [departmentAdmin, departmentServices],
  users,
  categories,
  items,
  requests,
  movements,
};
