create table departments (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    code varchar(32) not null unique,
    name varchar(128) not null,
    active boolean not null
);

create table app_users (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    full_name varchar(128) not null,
    email varchar(128) not null unique,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    role varchar(32) not null,
    department_id bigint null,
    position varchar(128) null,
    active boolean not null,
    constraint fk_app_users_department foreign key (department_id) references departments (id)
);

create table supply_categories (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    name varchar(128) not null unique,
    description varchar(255) null
);

create table supply_items (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    name varchar(128) not null,
    sku varchar(64) null unique,
    category_id bigint null,
    unit varchar(32) not null,
    current_quantity numeric(14,3) not null,
    min_quantity numeric(14,3) not null,
    storage_location varchar(128) null,
    description varchar(255) null,
    active boolean not null,
    constraint fk_supply_items_category foreign key (category_id) references supply_categories (id)
);

create table supply_requests (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    request_number varchar(32) not null unique,
    requester_id bigint not null,
    department_id bigint not null,
    status varchar(32) not null,
    priority varchar(32) not null,
    comment varchar(500) null,
    approved_by_id bigint null,
    approved_at timestamp null,
    rejection_reason varchar(500) null,
    constraint fk_supply_requests_requester foreign key (requester_id) references app_users (id),
    constraint fk_supply_requests_department foreign key (department_id) references departments (id),
    constraint fk_supply_requests_approved_by foreign key (approved_by_id) references app_users (id)
);

create table supply_request_items (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    request_id bigint not null,
    item_id bigint not null,
    quantity_requested numeric(14,3) not null,
    quantity_issued numeric(14,3) not null,
    note varchar(255) null,
    constraint fk_supply_request_items_request foreign key (request_id) references supply_requests (id) on delete cascade,
    constraint fk_supply_request_items_item foreign key (item_id) references supply_items (id)
);

create table stock_movements (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    type varchar(32) not null,
    item_id bigint not null,
    quantity numeric(14,3) not null,
    happened_at timestamp not null,
    source_document varchar(128) null,
    actor_id bigint null,
    request_id bigint null,
    comment varchar(500) null,
    constraint fk_stock_movements_item foreign key (item_id) references supply_items (id),
    constraint fk_stock_movements_actor foreign key (actor_id) references app_users (id),
    constraint fk_stock_movements_request foreign key (request_id) references supply_requests (id)
);

create index idx_supply_items_category_id on supply_items (category_id);
create index idx_supply_items_active on supply_items (active);
create index idx_supply_requests_requester_id on supply_requests (requester_id);
create index idx_supply_requests_department_id on supply_requests (department_id);
create index idx_supply_requests_status on supply_requests (status);
create index idx_supply_request_items_request_id on supply_request_items (request_id);
create index idx_supply_request_items_item_id on supply_request_items (item_id);
create index idx_stock_movements_item_id on stock_movements (item_id);
create index idx_stock_movements_request_id on stock_movements (request_id);
