create table request_chat_messages (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    request_id bigint not null,
    sender_id bigint not null,
    text varchar(2000) not null,
    constraint fk_request_chat_messages_request foreign key (request_id) references supply_requests (id) on delete cascade,
    constraint fk_request_chat_messages_sender foreign key (sender_id) references app_users (id)
);

create index idx_request_chat_messages_request_id on request_chat_messages (request_id);
create index idx_request_chat_messages_sender_id on request_chat_messages (sender_id);
create index idx_request_chat_messages_created_at on request_chat_messages (created_at);
