create table request_status_history (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    request_id bigint not null,
    actor_id bigint null,
    status varchar(32) not null,
    note varchar(500) null,
    constraint fk_request_status_history_request foreign key (request_id) references supply_requests (id) on delete cascade,
    constraint fk_request_status_history_actor foreign key (actor_id) references app_users (id)
);

create index idx_request_status_history_request_id on request_status_history (request_id);
create index idx_request_status_history_actor_id on request_status_history (actor_id);
create index idx_request_status_history_created_at on request_status_history (created_at);
