create table purchase_orders (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    order_number varchar(32) not null unique,
    status varchar(32) not null,
    comment varchar(500) null,
    created_by_id bigint not null,
    completed_at timestamp null,
    constraint fk_purchase_orders_created_by foreign key (created_by_id) references app_users (id)
);

create table purchase_order_items (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    purchase_order_id bigint not null,
    item_id bigint not null,
    quantity_ordered numeric(14,3) not null,
    constraint fk_purchase_order_items_order foreign key (purchase_order_id) references purchase_orders (id) on delete cascade,
    constraint fk_purchase_order_items_item foreign key (item_id) references supply_items (id)
);

create index idx_purchase_orders_created_by_id on purchase_orders (created_by_id);
create index idx_purchase_orders_status on purchase_orders (status);
create index idx_purchase_order_items_order_id on purchase_order_items (purchase_order_id);
create index idx_purchase_order_items_item_id on purchase_order_items (item_id);
