create table warehouses (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    code varchar(32) not null unique,
    name varchar(128) not null,
    description varchar(255) null,
    active boolean not null default true
);

create index idx_warehouses_code on warehouses (code);
create index idx_warehouses_name on warehouses (name);
