create table warehouse_stocks (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    warehouse_id bigint not null,
    item_id bigint not null,
    quantity numeric(14,3) not null,
    constraint fk_warehouse_stocks_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint fk_warehouse_stocks_item foreign key (item_id) references supply_items (id),
    constraint uq_warehouse_stocks_warehouse_item unique (warehouse_id, item_id)
);

insert into warehouse_stocks (created_at, updated_at, warehouse_id, item_id, quantity)
select now(), now(), w.id, si.id, coalesce(si.current_quantity, 0)
from supply_items si
join warehouses w on w.name = si.storage_location
where coalesce(si.current_quantity, 0) <> 0;

create index idx_warehouse_stocks_warehouse_id on warehouse_stocks (warehouse_id);
create index idx_warehouse_stocks_item_id on warehouse_stocks (item_id);
